variable keycloak_namespace {
  type        = string
  default     = "ingestion-app"
  description = "namespace for keycloak"
}
variable image_registry {
  type        = string
  default     = "660061364911.dkr.ecr.ap-south-1.amazonaws.com"
  description = "Keycloak image registry"
}
variable image_repository {
  type        = string
  default     = "keycloack"
  description = "Key cloak image repository"
}
variable image_tag {
  type        = string
  default     = "base"
  description = "image tag"
}
variable adminUser {
  type        = string
  default     = "admin"
  description = "admin username"
}
variable adminPassword {
  type        = string
  default     = "Password123" //CHANGE IT
  description = "password for admin user"
}
variable tls_enabled {
  default     = true
  description = "tls enabled"
}
variable tls_autoGenerated {
  default     = true
  description = "auto generate tls certificate"
}
variable production {
  default     = true
  description = "production"
}
variable httpRelativePath {
  type        = string
  default     = "/auth/"
  description = "relatve path"
}
variable service_type {
  type        = string
  default     = "ClusterIP"
  description = "service type"
}
variable externalDatabase_host {
  type        = string
  default     = "pryzm-db.cepsv5f9ayrr.ap-south-1.rds.amazonaws.com"
  description = "Host for external postgres DB"
}
variable externalDatabase_port {
  default     = 5432
  description = "database port"
}
variable externalDatabase_user {
  type        = string
  default     = "postgres"
  description = "external user name"
}
variable externalDatabase_database {
  type        = string
  default     = "test_keycloak_db"
  description = "external postgres db name"
}
variable externalDatabase_password {
  type        = string
  default     = "lumiq123"
  description = "external db password"
}