deployment:
  name: empoweringestionconnectionservice
  replicas: 1
  image: 660061364911.dkr.ecr.ap-south-1.amazonaws.com/empower-ingestion-connection-service:6
  containerPort: 6200
  cpu: 300m
  env:
    port: "6200"
    host: "0.0.0.0"
service:
  name: empoweringestionconnectionservice
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    #service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-03fc40e8f2c87cb10,subnet-0e00434f6bceffa21
  port: 80
  targetPort: 6200

