apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: {{ .Values.virtualService1.name }}
spec:
  gateways:
  - {{ .Values.virtualService1.gateway }}
  hosts:
  - '{{ .Values.virtualService1.host }}'
  http:
  - match:
    - uri:
        prefix: '{{ .Values.virtualService1.uriPrefix }}'
    - uri:
        prefix: '{{ .Values.virtualService1.uriPrefixWithoutSlash }}'
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.virtualService1.destination.host }}
        port:
          number: {{ .Values.virtualService1.destination.port }}
