{{- $deployment := .Values.deployment -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        env:
          - name: PORT
            value: "{{ .Values.deployment.env.port }}"
          - name: HOST
            value: "{{ .Values.deployment.env.host }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.deployment.cpu }}

